name: verman
description: A friendly neighborhood version manager for Flutter projects. Automates versioning across pubspec.yaml, build.gradle, and Info.plist.
version: 1.1.3+4
homepage: https://github.com/artkinx/vermanCLI
repository: https://github.com/artkinx/vermanCLI
topics:
  - version
  - automation
  - flutter
  - cli
platforms:
    ios: 
    android: 

executables:
  verman:

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
